# Generated by Django 4.2.7 on 2025-09-07 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SportAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="assessment_videos/")),
                (
                    "sport_type",
                    models.CharField(
                        choices=[
                            ("Javelin Throw", "Javelin Throw"),
                            ("Table Tennis", "Table Tennis"),
                            ("Archery", "Archery"),
                            ("Push-ups", "Push-ups"),
                            ("Discus Throw", "Discus Throw"),
                            ("High Jump", "High Jump"),
                        ],
                        max_length=50,
                    ),
                ),
                ("predicted_sport", models.CharField(blank=True, max_length=50)),
                ("metrics", models.TextField(blank=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
